apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-sim
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sensor-sim
  template:
    metadata:
      labels:
        app: sensor-sim
    spec:
      initContainers:
      - name: wait-for-mqtt
        image: busybox
        command: ['sh', '-c', 'until nc -z mosquitto-service 1883; do echo waiting for mqtt; sleep 5; done;']
      containers:
      - name: sensor-sim
        image: abhishek6126/sensor-sim:latest
        imagePullPolicy: Always
        env:
        - name: MQTT_BROKER
          value: "mosquitto-service"
        - name: MQTT_PORT
          value: "1883"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-sim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller-sim
  template:
    metadata:
      labels:
        app: controller-sim
    spec:
      initContainers:
      - name: wait-for-mqtt
        image: busybox
        command: ['sh', '-c', 'until nc -z mosquitto-service 1883; do echo waiting for mqtt; sleep 5; done;']
      containers:
      - name: controller-sim
        image: abhishek6126/controller-sim:latest
        imagePullPolicy: Always
        env:
        - name: MQTT_BROKER
          value: "mosquitto-service"
        - name: MQTT_PORT
          value: "1883"
